### 텐서의 생성 및 변환
* 텐서 : 파이토치의 가장 기본이 되는 데이터 구조

(1) 텐서의 생성

In [1]:
import torch

## 2차원의 텐서 생성
print(torch.tensor([[1,2], [3,4]]))
## GPU에 텐서 생성
print(torch.tensor([[1,2], [3,4]], device="cuda:0"))
## dtype을 이용하여 텐서를 생성
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


(2) 텐서를 ndarray로 변환

In [7]:
import numpy

temp = torch.tensor([[1,2], [3,4]])
print("temp : \n", temp.numpy())
print("Type of temp : ", type(temp.numpy()))

print("-------------------------------------")

temp = torch.tensor([[1,2], [3,4]], device="cuda:0")
print("temp : \n", temp.to("cpu").numpy())
print("Type of temp : ",type(temp.to("cpu").numpy()))

temp : 
 [[1 2]
 [3 4]]
Type of temp :  <class 'numpy.ndarray'>
-------------------------------------
temp : 
 [[1 2]
 [3 4]]
Type of temp :  <class 'numpy.ndarray'>


(3) 텐서의 인덱스 조절

In [8]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])

print(temp[0], temp[1], temp[-1])
print("----------------------------------")
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
----------------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


(4) 텐서의 연산

In [9]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print("w : ", w)
print("v : ", v)
print("w - v : ", w-v)

w :  tensor([3, 4, 6])
v :  tensor([1, 2, 3])
w - v :  tensor([2, 2, 3])


(5) 텐서의 차원 조작

In [17]:
temp = torch.tensor([[1,2], [3,4]])
print("[Original temp]\n", temp)
print("Original temp shape : ", temp.shape)
print("-------------------------------------")
print("[Reshape (4, 1)] \n", temp.view(4,1))
print("--------------------------------------")
print("[Reshape (-1)] = 차원 하나 \n", temp.view(-1))
print("--------------------------------------")
print("[Reshape (1, -1)  = (1, 4)] \n", temp.view(1, -1))
print("--------------------------------------")
print("[Reshape (-1, 1) = (4, 1)] \n", temp.view(-1, 1))

[Original temp]
 tensor([[1, 2],
        [3, 4]])
Original temp shape :  torch.Size([2, 2])
-------------------------------------
[Reshape (4, 1)] 
 tensor([[1],
        [2],
        [3],
        [4]])
--------------------------------------
[Reshape (-1)] = 차원 하나 
 tensor([1, 2, 3, 4])
--------------------------------------
[Reshape (1, -1)  = (1, 4)] 
 tensor([[1, 2, 3, 4]])
--------------------------------------
[Reshape (-1, 1) = (4, 1)] 
 tensor([[1],
        [2],
        [3],
        [4]])
