In [4]:
import torch

print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2], [3,4]], device="cuda:0"))
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy())

[[1 2]
 [3 4]]


In [6]:
temp = torch.tensor([[1,2], [3,4]], device="cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]


In [13]:
# 텐서의 인덱스 조절
temp = torch.FloatTensor([1,2,3,4,5,6,7])

print(temp[0], temp[1], temp[-1])
print("----------------------------------")
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
----------------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [14]:
# 텐서의 연산
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w - v)

tensor([2, 2, 3])


In [15]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.shape)
print("-------------------------------------")
print(temp.view(4,1))
print("--------------------------------------")
print(temp.view(-1))
print("--------------------------------------")
print(temp.view(1, -1))
print("--------------------------------------")
print(temp.view(-1, 1))

torch.Size([2, 2])
-------------------------------------
tensor([[1],
        [2],
        [3],
        [4]])
--------------------------------------
tensor([1, 2, 3, 4])
--------------------------------------
tensor([[1, 2, 3, 4]])
--------------------------------------
tensor([[1],
        [2],
        [3],
        [4]])
