In [ ]:
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.])

print(t)
print("Rank of t : ", t.ndim)
print("Shape of t : ", t.shape)

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

print(t)
print("Rank of t :", t.ndim)    
print("Shape of t : ", t.shape)

In [11]:
import torch

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(type(t))

print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
<class 'torch.Tensor'>
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
t = torch.Tensor(7)

print(t)
print(t.dim())
print(t.shape)
print(t.size())

tensor([-3.6862e+36,  4.5773e-41,  1.1986e-35,  0.0000e+00,  1.4013e-45,
         0.0000e+00,  0.0000e+00])
1
torch.Size([7])
torch.Size([7])


In [12]:
t = torch.cuda.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(type(t))

tensor([0., 1., 2., 3., 4., 5., 6.], device='cuda:0')
1
torch.Size([7])
torch.Size([7])
<class 'torch.Tensor'>


In [13]:
import torch
import numpy as np

t1 = np.array([1, 2, 3, 4])
t2 = torch.Tensor(t1)

print(t1, type(t1))
print(t2, type(t2))

[1 2 3 4] <class 'numpy.ndarray'>
tensor([1., 2., 3., 4.]) <class 'torch.Tensor'>


In [14]:
import torch
import numpy as np

t1 = torch.rand(3, 3)
t2 = t1.numpy()

print(t1, type(t1))
print(t2, type(t2))

tensor([[0.6114, 0.0674, 0.4300],
        [0.3737, 0.5329, 0.1998],
        [0.5328, 0.8768, 0.3145]]) <class 'torch.Tensor'>
[[0.61136174 0.06737643 0.429964  ]
 [0.37373132 0.532862   0.19983405]
 [0.5327635  0.8767636  0.31454396]] <class 'numpy.ndarray'>


In [16]:
import torch

t1 = torch.randn(1, 1, 3, 3)
t2 = torch.randn(1, 1, 3, 3)
t3 = torch.cat((t1, t2), 0)

print(t1)
print(t2)
print(t3)

tensor([[[[-0.5026, -1.0684, -1.0123],
          [ 0.2076,  0.3000,  0.6204],
          [ 1.2220,  0.8290,  0.0368]]]])
tensor([[[[-0.3171,  0.1182, -2.0305],
          [ 1.0928,  1.5061, -0.2086],
          [ 0.7133,  1.0139, -2.2112]]]])
tensor([[[[-0.5026, -1.0684, -1.0123],
          [ 0.2076,  0.3000,  0.6204],
          [ 1.2220,  0.8290,  0.0368]]],


        [[[-0.3171,  0.1182, -2.0305],
          [ 1.0928,  1.5061, -0.2086],
          [ 0.7133,  1.0139, -2.2112]]]])


In [30]:
import torch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])

print(t)
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [34]:
import torch

x = torch.rand(3, 3)
y = torch.rand(3, 3)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    sum = x + y
    print(sum)
    
else:
    print("GPU 지원 안됨!")

tensor([[0.5279, 1.6061, 1.1269],
        [1.4931, 1.1967, 0.6613],
        [1.0208, 0.7873, 0.9840]], device='cuda:0')


In [35]:
import torch

x = torch.rand(3, 3)
x_mean = x.mean()
x_sum = x.sum()

print(x_mean, x_sum)

tensor(0.3506) tensor(3.1550)


In [37]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print("Shape of Matrix 1 : ", m1.shape)
print("Shape of Matrix 2 : ", m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [39]:
m1 = torch.FloatTensor(([1, 2], [3, 4]))
m2 = torch.FloatTensor(([1], [2]))

print("Shape of Matrix 1 : ", m1.shape)
print("Shape of Matrix 2 : ", m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [41]:
# 크기가 같은 텐서의 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# 크기가 다른 텐서의 연산
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

# 벡터 간 연산에서 브로드캐스팅
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [43]:
t = np.array([[[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

torch.Size([1, 4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [46]:
import torch
from torch.autograd import Variable

x = torch.ones(2, 2)
x = Variable(x, requires_grad=True)
print(x)
print(x.data)
print(x.grad_fn)
print("=========================================")

y = x + 2
print(y)
print("=========================================")

z = y ** 2
print(z)
print("=========================================")

out = z.sum()
print(out)
print("=========================================")

out.backward()
print(x.data)
print(x.grad)
print(x.grad_fn)
print("=========================================")

print(y.data)
print(y.grad)
print(y.grad_fn)
print("=========================================")

print(z.data)
print(z.grad)
print(z.grad_fn)
print("=========================================")

print(out.data)
print(out.grad)
print(out.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)
tensor(36., grad_fn=<SumBackward0>)
tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None
tensor([[3., 3.],
        [3., 3.]])
None
tensor([[9., 9.],
        [9., 9.]])
None
tensor(36.)
None


/home/sydney/Desktop/2022_SELF_STUDY/딥러닝파이토치교과서/DeepLearningPytorch_venv/lib/python3.8/site-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:475.)
  return self._grad


In [48]:
import torch
from torch.autograd import Variable
x = torch.ones(3)
x = Variable(x, requires_grad=True)
y = x ** 2
z = y * 3
print(z)

grad = torch.Tensor([0.1, 1, 10])
z.backward(grad)

print("-----x.data-----")
print(x.data)

print("-----x.grad-----")
print(x.grad)

print("-----x.grad_fn-----")
print(x.grad_fn)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)
-----x.data-----
tensor([1., 1., 1.])
-----x.grad-----
tensor([ 0.6000,  6.0000, 60.0000])
-----x.grad_fn-----
None


In [52]:
import torch.nn as nn

m = nn.Conv2d(16, 22, 2, stride=2)
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
m = nn.Conv2d(16, 33, (3, 4), stride=(2, 1), padding=(4, 2), dilation = (3, 1))

input = torch.randn(20, 16, 50, 100)
output = m(input)
print(input.shape)
print(output.shape)

torch.Size([20, 16, 50, 100])
torch.Size([20, 33, 26, 101])


In [55]:
import torch.autograd as autograd
import torch.nn.functional as F

filters = autograd.Variable(torch.randn(8, 4, 3, 3))
inputs = autograd.Variable(torch.randn(1, 4, 5, 5))
result = F.conv2d(inputs, filters, padding=1)
print(result.shape)

torch.Size([1, 8, 5, 5])


In [59]:
import torch
from torch.autograd import Variable
import torch.nn.functional as F

input = torch.ones(1, 1, 3, 3)
filter = torch.ones(1, 1, 3, 3)
input = Variable(input, requires_grad=True)
print(input)

filter = Variable(filter, requires_grad=True)
out = F.conv2d(input, filter)
print(out.grad_fn)

out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [60]:
import torch
from torch.autograd import Variable
import torch.nn as nn

input = torch.ones(1, 1, 3, 3)
input = Variable(input, requires_grad=True)
filter = nn.Conv2d(1, 1, 3)
filter.weight
out = filter(input)
print(out)
print(input.grad)

out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[0.0123]]]], grad_fn=<ConvolutionBackward0>)
None
tensor([[[[-0.2758,  0.3023,  0.1220],
          [-0.2933,  0.1815,  0.0030],
          [ 0.1870,  0.2389, -0.2119]]]])


In [61]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

input = torch.ones(1, 1 ,5, 5)
input = Variable(input, requires_grad=True)
filter = nn.Conv2d(1, 1, 3, bias=None)
print(filter.weight)

filter.weight = nn.Parameter(torch.ones(1, 1, 3, 3) +1)
filter.weight
out = filter(input)
print(out)

Parameter containing:
tensor([[[[-0.2789, -0.2687, -0.2579],
          [ 0.2115, -0.2454,  0.3047],
          [-0.2023,  0.1667, -0.0384]]]], requires_grad=True)
tensor([[[[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]], grad_fn=<ConvolutionBackward0>)


In [63]:
import torch
import numpy as np
import torch.nn as nn
import torch.autograd.profiler as profiler

class MyModule(nn.Module):
    def __init__(self, in_features: int, out_features: int, bias: bool = True):
        super(MyModule, self).__init__()
        self.linear = nn.Linear(in_features, out_features, bias)

    def forward(self, input, mask):
        with profiler.record_function("LINEAR PASS"):
            out = self.linear(input)
        with profiler.record_function("MASK INDICES"):
            threshold = out.sum(axis=1).mean().item()
            hi_idx = np.argwhere(mask.cpu().numpy() > threshold)
            hi_idx = torch.from_numpy(hi_idx).cuda()

        return out, hi_idx

In [64]:
import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(0.5, 0.5, 0.5), (0.5, 0.5, 0.5)])

In [65]:
import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(),
                                transforms.CenterCrop(10)])

In [66]:
import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5, 0.5), (0.5, 0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root="./",
                                        train=True,
                                        download=True,
                                        transform=transform)

testset = torchvision.datasets.CIFAR10(root="./",
                                       train=False,
                                       download=True,
                                       transform=transform)

1.4%


KeyboardInterrupt: 

In [67]:
from torch.utils.data import DataLoader
import argparse as args

imagenet_data = torchvision.datasets.ImageNet("/")
data_loader = DataLoader(imagenet_data,
                        batch_size=4,
                        shuffle=True,
                        num_worker=args.nThreads)

ModuleNotFoundError: No module named 'scipy'

In [68]:
class my_network(nn.Module):
    def __int__(self):
        super(my_network, self).__init__()
        # 사용할 함수 정의
    def forward(self, x):
        # forward 구조

SyntaxError: unexpected EOF while parsing (403691287.py, line 6)

In [72]:
import numpy as np

x_train = np.array([[1], [2], [3]])
y_train = np.array([[2], [4], [6]])

w = 0
b = 0
lr = 0.01
n_data = len(x_train)
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    hypothesis = x_train * w + b
    cost = np.sum((hypothesis - y_train) * 2 *x_train) / n_data
    gradient_w = np.sum((hypothesis - y_train) * 2 * x_train) / n_data
    gradient_b = np.sum((hypothesis - y_train) * 2) / n_data
    w -= lr * gradient_w
    b -= lr * gradient_b
    if epoch % 100 == 0:
        print("Epoch {:4d} / {} w: {:.3f}, b: {:.3f} cost: {:.6f}".format(epoch, nb_epochs, w, b, cost))

Epoch    0 / 2000 w: 0.187, b: 0.080 cost: -18.666667
Epoch  100 / 2000 w: 1.746, b: 0.578 cost: -0.061424
Epoch  200 / 2000 w: 1.800, b: 0.454 cost: -0.048171
Epoch  300 / 2000 w: 1.843, b: 0.357 cost: -0.037866
Epoch  400 / 2000 w: 1.876, b: 0.281 cost: -0.029766
Epoch  500 / 2000 w: 1.903, b: 0.221 cost: -0.023399
Epoch  600 / 2000 w: 1.924, b: 0.174 cost: -0.018394
Epoch  700 / 2000 w: 1.940, b: 0.136 cost: -0.014459
Epoch  800 / 2000 w: 1.953, b: 0.107 cost: -0.011366
Epoch  900 / 2000 w: 1.963, b: 0.084 cost: -0.008935
Epoch 1000 / 2000 w: 1.971, b: 0.066 cost: -0.007024
Epoch 1100 / 2000 w: 1.977, b: 0.052 cost: -0.005521
Epoch 1200 / 2000 w: 1.982, b: 0.041 cost: -0.004340
Epoch 1300 / 2000 w: 1.986, b: 0.032 cost: -0.003412
Epoch 1400 / 2000 w: 1.989, b: 0.025 cost: -0.002682
Epoch 1500 / 2000 w: 1.991, b: 0.020 cost: -0.002108
Epoch 1600 / 2000 w: 1.993, b: 0.016 cost: -0.001657
Epoch 1700 / 2000 w: 1.995, b: 0.012 cost: -0.001303
Epoch 1800 / 2000 w: 1.996, b: 0.010 cost: -0

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

hypothesis = x_train * w + b
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

optimizer = optim.SGD([w, b], lr=0.01)
optimizer.zero_grad()

cost.backward()

optimizer.step()



In [79]:
import torch.optim as optim

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w, b], lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    hypothesis = x_train * w + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0 :
        print("Epoch {:4d}/{} w: {:.3f} b: {:.3f} cost: {:.6f}".format(epoch, nb_epochs, w.item(), b.item(), cost.item()))

Epoch    0/2000 w: 0.187 b: 0.080 cost: 18.666666
Epoch  100/2000 w: 1.746 b: 0.578 cost: 0.048171
Epoch  200/2000 w: 1.800 b: 0.454 cost: 0.029767
Epoch  300/2000 w: 1.843 b: 0.357 cost: 0.018394
Epoch  400/2000 w: 1.876 b: 0.281 cost: 0.011366
Epoch  500/2000 w: 1.903 b: 0.221 cost: 0.007024
Epoch  600/2000 w: 1.924 b: 0.174 cost: 0.004340
Epoch  700/2000 w: 1.940 b: 0.136 cost: 0.002682
Epoch  800/2000 w: 1.953 b: 0.107 cost: 0.001657
Epoch  900/2000 w: 1.963 b: 0.084 cost: 0.001024
Epoch 1000/2000 w: 1.971 b: 0.066 cost: 0.000633
Epoch 1100/2000 w: 1.977 b: 0.052 cost: 0.000391
Epoch 1200/2000 w: 1.982 b: 0.041 cost: 0.000242
Epoch 1300/2000 w: 1.986 b: 0.032 cost: 0.000149
Epoch 1400/2000 w: 1.989 b: 0.025 cost: 0.000092
Epoch 1500/2000 w: 1.991 b: 0.020 cost: 0.000057
Epoch 1600/2000 w: 1.993 b: 0.016 cost: 0.000035
Epoch 1700/2000 w: 1.995 b: 0.012 cost: 0.000022
Epoch 1800/2000 w: 1.996 b: 0.010 cost: 0.000013
Epoch 1900/2000 w: 1.997 b: 0.008 cost: 0.000008
Epoch 2000/2000 w: 

In [80]:
import torch

w = torch.tensor(2.0, requires_grad=True)
y = w ** 2
z = 2*y + 5

z.backward()
print("수식을 w로 미분한 값 : {}".format(w.grad))

수식을 w로 미분한 값 : 8.0


In [91]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)
nb_epochs = 500000
for epoch in range(nb_epochs + 1):
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10000 == 0:
        print("Epoch {:4d}/{} w1: {:.3f}  w2: {:.3f}  w3: {:.3f} b: {:.3f} cost: {:.6f}".format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))

Epoch    0/500000 w1: 0.294  w2: 0.294  w3: 0.297 b: 0.003 cost: 29661.800781
Epoch 10000/500000 w1: 0.888  w2: 0.464  w3: 0.658 b: 0.020 cost: 0.271223
Epoch 20000/500000 w1: 0.933  w2: 0.466  w3: 0.612 b: 0.028 cost: 0.227067
Epoch 30000/500000 w1: 0.960  w2: 0.478  w3: 0.574 b: 0.036 cost: 0.203368
Epoch 40000/500000 w1: 0.980  w2: 0.488  w3: 0.544 b: 0.042 cost: 0.188761
Epoch 50000/500000 w1: 0.996  w2: 0.496  w3: 0.521 b: 0.048 cost: 0.179741
Epoch 60000/500000 w1: 1.008  w2: 0.502  w3: 0.502 b: 0.053 cost: 0.174160
Epoch 70000/500000 w1: 1.018  w2: 0.507  w3: 0.488 b: 0.058 cost: 0.170693
Epoch 80000/500000 w1: 1.025  w2: 0.510  w3: 0.477 b: 0.062 cost: 0.168531
Epoch 90000/500000 w1: 1.031  w2: 0.513  w3: 0.468 b: 0.066 cost: 0.167169
Epoch 100000/500000 w1: 1.036  w2: 0.516  w3: 0.461 b: 0.070 cost: 0.166304
Epoch 110000/500000 w1: 1.039  w2: 0.517  w3: 0.456 b: 0.073 cost: 0.165734
Epoch 120000/500000 w1: 1.042  w2: 0.519  w3: 0.452 b: 0.076 cost: 0.165365
Epoch 130000/500000

In [100]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

x_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

print(x_train.shape)
print(y_train.shape)

w = torch.zeros((1, 5), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    hypothesis = x_train.matmul(w) + b
    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print("Epoch {:4d}/{} hypothesis: {} cost: {:.6f}".format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

torch.Size([5, 1])
torch.Size([5, 1])
Epoch    0/20 hypothesis: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) cost: 29661.800781
Epoch    1/20 hypothesis: tensor([[18.0378, 18.0378, 18.0378, 18.0378, 18.0378],
        [21.9532, 21.9532, 21.9532, 21.9532, 21.9532],
        [21.3599, 21.3599, 21.3599, 21.3599, 21.3599],
        [23.2583, 23.2583, 23.2583, 23.2583, 23.2583],
        [16.8513, 16.8513, 16.8513, 16.8513, 16.8513]]) cost: 23039.744141
Epoch    2/20 hypothesis: tensor([[33.9351, 33.9351, 33.9351, 33.9351, 33.9351],
        [41.3012, 41.3012, 41.3012, 41.3012, 41.3012],
        [40.1851, 40.1851, 40.1851, 40.1851, 40.1851],
        [43.7566, 43.7566, 43.7566, 43.7566, 43.7566],
        [31.7029, 31.7029, 31.7029, 31.7029, 31.7029]]) cost: 17896.076172
Epoch    3/20 hypothesis: tensor([[47.9459, 47.9459, 47.9459, 47.9459, 47.9459],
        [58.3533, 58.3533, 58.3533, 58.3533

In [ ]:
import torch.nn as nn
model = nn.Linear(input_dim, output_dim)

import torch.nn.functional as F
cost = F.mse_loss(prediction, y_train)

In [101]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(1, 1)
print(list(model.parameters()))

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print("Epoch {:4d}/{} cost: {:.6f}".format(epoch, nb_epochs, cost.item()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch    0/2000 cost: 13.103541
Epoch  100/2000 cost: 0.002791
Epoch  200/2000 cost: 0.001724
Epoch  300/2000 cost: 0.001066
Epoch  400/2000 cost: 0.000658
Epoch  500/2000 cost: 0.000407
Epoch  600/2000 cost: 0.000251
Epoch  700/2000 cost: 0.000155
Epoch  800/2000 cost: 0.000096
Epoch  900/2000 cost: 0.000059
Epoch 1000/2000 cost: 0.000037
Epoch 1100/2000 cost: 0.000023
Epoch 1200/2000 cost: 0.000014
Epoch 1300/2000 cost: 0.000009
Epoch 1400/2000 cost: 0.000005
Epoch 1500/2000 cost: 0.000003
Epoch 1600/2000 cost: 0.000002
Epoch 1700/2000 cost: 0.000001
Epoch 1800/2000 cost: 0.000001
Epoch 1900/2000 cost: 0.000000
Epoch 2000/2000 cost: 0.000000


In [102]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [104]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3, 1)

print(list(model.parameters()))

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs +1):
    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()

    cost.backward()

    optimizer.step()

    if epoch % 100 == 0 :
        print("Epoch {:4d}/{} cost: {:.6f}".format(epoch, nb_epochs, cost.item()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Epoch    0/2000 cost: 31667.597656
Epoch  100/2000 cost: 0.225993
Epoch  200/2000 cost: 0.223911
Epoch  300/2000 cost: 0.221941
Epoch  400/2000 cost: 0.220059
Epoch  500/2000 cost: 0.218271
Epoch  600/2000 cost: 0.216575
Epoch  700/2000 cost: 0.214950
Epoch  800/2000 cost: 0.213413
Epoch  900/2000 cost: 0.211952
Epoch 1000/2000 cost: 0.210560
Epoch 1100/2000 cost: 0.209232
Epoch 1200/2000 cost: 0.207967
Epoch 1300/2000 cost: 0.206761
Epoch 1400/2000 cost: 0.205619
Epoch 1500/2000 cost: 0.204522
Epoch 1600/2000 cost: 0.203484
Epoch 1700/2000 cost: 0.202485
Epoch 1800/2000 cost: 0.201542
Epoch 1900/2000 cost: 0.200635
Epoch 2000/2000 cost: 0.199769


In [105]:
# 단순 선형회귀 모델
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
    
    def forward(self, x):
        return self.Linear(x)

model = LinearRegressionModel()

# 다중 선형회귀 모델
class MultivariatedLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

model = MultivariatedLinearRegressionModel()

In [108]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 5

for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples

        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        print("Epoch {:4d}/{} Batch {}/{} cost: {:.6f}".format(
            epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()
        ))

Epoch    0/5 Batch 1/3 cost: 9264.955078
Epoch    0/5 Batch 2/3 cost: 1297.079834
Epoch    0/5 Batch 3/3 cost: 892.334229
Epoch    1/5 Batch 1/3 cost: 211.432770
Epoch    1/5 Batch 2/3 cost: 50.638744
Epoch    1/5 Batch 3/3 cost: 19.237814
Epoch    2/5 Batch 1/3 cost: 9.107946
Epoch    2/5 Batch 2/3 cost: 0.700511
Epoch    2/5 Batch 3/3 cost: 0.570977
Epoch    3/5 Batch 1/3 cost: 1.513565
Epoch    3/5 Batch 2/3 cost: 0.128820
Epoch    3/5 Batch 3/3 cost: 0.013758
Epoch    4/5 Batch 1/3 cost: 0.035176
Epoch    4/5 Batch 2/3 cost: 0.109691
Epoch    4/5 Batch 3/3 cost: 2.018996
Epoch    5/5 Batch 1/3 cost: 0.640522
Epoch    5/5 Batch 2/3 cost: 0.505552
Epoch    5/5 Batch 3/3 cost: 0.005554


In [109]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        # 데이터 전처리
    def __len__(self):
        # 데이터셋의 길이, 즉 샘플의 총 수를 적는 부분
    def __getitem__(self, idx):
        # 데이터셋에서 특정 1개의 샘플을 가져오는 함수

IndentationError: expected an indented block (1672926917.py, line 4)

In [6]:
import torch
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]

        self.y_data = [[152], [185], [180], [196], [142]]

    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 5
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        print("Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}".format(epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))

Epoch    0/5 Batch 1/3 Cost: 27377.451172
Epoch    0/5 Batch 2/3 Cost: 14383.236328
Epoch    0/5 Batch 3/3 Cost: 1639.672852
Epoch    1/5 Batch 1/3 Cost: 897.473389
Epoch    1/5 Batch 2/3 Cost: 563.536865
Epoch    1/5 Batch 3/3 Cost: 100.977417
Epoch    2/5 Batch 1/3 Cost: 8.344945
Epoch    2/5 Batch 2/3 Cost: 27.861610
Epoch    2/5 Batch 3/3 Cost: 23.496368
Epoch    3/5 Batch 1/3 Cost: 8.535181
Epoch    3/5 Batch 2/3 Cost: 3.684837
Epoch    3/5 Batch 3/3 Cost: 5.614924
Epoch    4/5 Batch 1/3 Cost: 0.758023
Epoch    4/5 Batch 2/3 Cost: 12.610233
Epoch    4/5 Batch 3/3 Cost: 13.243709
Epoch    5/5 Batch 1/3 Cost: 6.475133
Epoch    5/5 Batch 2/3 Cost: 8.670555
Epoch    5/5 Batch 3/3 Cost: 3.423539


In [14]:
import torch.optim as optim

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

w = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = torch.sigmoid(x_train.matmul(w) + b)
    cost = -(y_train*torch.log(hypothesis) + (1-y_train)*torch.log(1-hypothesis)).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print("Epoch {:4d}/{} cost: {:.6f}".format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 cost: 0.693147
Epoch  100/1000 cost: 0.134722
Epoch  200/1000 cost: 0.080643
Epoch  300/1000 cost: 0.057900
Epoch  400/1000 cost: 0.045300
Epoch  500/1000 cost: 0.037261
Epoch  600/1000 cost: 0.031673
Epoch  700/1000 cost: 0.027556
Epoch  800/1000 cost: 0.024394
Epoch  900/1000 cost: 0.021888
Epoch 1000/1000 cost: 0.019852


In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

print(model(x_train))

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs+1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print("Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%".format(
            epoch, nb_epochs, cost.item(), accuracy*100
        ))

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)
Epoch    0/100 Cost: 0.539713 Accuracy 83.33%
Epoch   10/100 Cost: 0.614853 Accuracy 66.67%
Epoch   20/100 Cost: 0.441875 Accuracy 66.67%
Epoch   30/100 Cost: 0.373145 Accuracy 83.33%
Epoch   40/100 Cost: 0.316358 Accuracy 83.33%
Epoch   50/100 Cost: 0.266094 Accuracy 83.33%
Epoch   60/100 Cost: 0.220498 Accuracy 100.00%
Epoch   70/100 Cost: 0.182095 Accuracy 100.00%
Epoch   80/100 Cost: 0.157299 Accuracy 100.00%
Epoch   90/100 Cost: 0.144091 Accuracy 100.00%
Epoch  100/100 Cost: 0.134272 Accuracy 100.00%


In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

print(x_train.shape)
print(y_train.shape)

y_one_hot = torch.zeros(8, 3)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot.shape)

w = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w, b], lr=0.001)

nb_epochs = 10000
for epoch in range(nb_epochs + 1):
    z = x_train.matmul(w) + b
    cost = F.cross_entropy(z, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 1000 == 0:
        print("Epoch {:4d}/{} cost: {:.6f}".format(epoch, nb_epochs, cost.item()))

torch.Size([8, 4])
torch.Size([8])
torch.Size([8, 3])
Epoch    0/10000 cost: 1.098612
Epoch 1000/10000 cost: 0.851076
Epoch 2000/10000 cost: 0.785051
Epoch 3000/10000 cost: 0.744691
Epoch 4000/10000 cost: 0.714731
Epoch 5000/10000 cost: 0.690764
Epoch 6000/10000 cost: 0.670850
Epoch 7000/10000 cost: 0.653893
Epoch 8000/10000 cost: 0.639185
Epoch 9000/10000 cost: 0.626237
Epoch 10000/10000 cost: 0.614693


In [37]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(777)
if device == "cuda":
    torch.cuda.manual_seed_all(777)

x = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]]).to(device)
y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model =  nn.Sequential(linear, sigmoid).to(device)

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(x)
    cost = criterion(hypothesis, y)
    cost.backward()
    optimizer.step()
    if step % 1000 == 0:
        print(step, cost.item())

0 0.7273974418640137
1000 0.6931471824645996
2000 0.6931471824645996
3000 0.6931471824645996
4000 0.6931471824645996
5000 0.6931471824645996
6000 0.6931471824645996
7000 0.6931471824645996
8000 0.6931471824645996
9000 0.6931471824645996
10000 0.6931471824645996


In [40]:
import torch
import torch.nn as nn
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(777)
if device == "cuda":
    torch.cuda.manual_seed_all(777)

x = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]]).to(device)
y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

model = nn.Sequential(
    nn.Linear(2, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 1, bias=True),
    nn.Sigmoid()
    ).to(device)

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

for epoch in range(10001):
    optimizer.zero_grad()
    hypothesis = model(x)

    cost = criterion(hypothesis, y)
    cost.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(epoch, cost.item())

0 0.6948983669281006
1000 0.6931380033493042
2000 0.6931172609329224
3000 0.6930763721466064
4000 0.6929103136062622
5000 0.6820817589759827
6000 0.0013030603295192122
7000 0.00048370816512033343
8000 0.0002889616880565882
9000 0.00020376498287077993
10000 0.00015648972475901246


In [3]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import matplotlib.pyplot as plt
import random

USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")
print("다음 기기로 학습합니다 : ", device)

random.seed(777)
torch.manual_seed(777)
if device == "cuda":
    torch.cuda.manual_seed_all(777)

mnist_train = dsets.MNIST(root = "",
                          train = True,
                          transform=transforms.ToTensor(),
                          download=True)
mnist_test  = dsets.MNIST(root="",
                          train = False,
                          transform=transforms.ToTensor(),
                          download=True)

data_loader = DataLoader(dataset=mnist_train,
                         batch_size=100,
                         shuffle=True,
                         drop_last=True)

linear = nn.Linear(784, 10, bias=True).to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(linear.parameters(), lr=0.1)

training_epochs = 20

for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(data_loader)

    for x, y in data_loader:
        x = x.view(-1, 28*28).to(device)
        y = y.to(device)
        optimizer.zero_grad()
        hypothesis = linear(x)
        cost = criterion(hypothesis, y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print("Epoch: ", "%04d" % (epoch + 1), "cost = ", "{:.9f}".format(avg_cost))

print("Learning finished")

다음 기기로 학습합니다 :  cuda
Epoch:  0001 cost =  0.535150588
Epoch:  0002 cost =  0.359577715
Epoch:  0003 cost =  0.331264287
Epoch:  0004 cost =  0.316404670
Epoch:  0005 cost =  0.307107002
Epoch:  0006 cost =  0.300456554
Epoch:  0007 cost =  0.294933408
Epoch:  0008 cost =  0.290956199
Epoch:  0009 cost =  0.287074089
Epoch:  0010 cost =  0.284515619
Epoch:  0011 cost =  0.281914055
Epoch:  0012 cost =  0.279526860
Epoch:  0013 cost =  0.277636588
Epoch:  0014 cost =  0.275874794
Epoch:  0015 cost =  0.274422765
Epoch:  0016 cost =  0.272883624
Epoch:  0017 cost =  0.271629572
Epoch:  0018 cost =  0.270609796
Epoch:  0019 cost =  0.269295007
Epoch:  0020 cost =  0.268277347
Learning finished


In [7]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
import random

USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")
print("다음 기기로 학습합니다 : ", device)

random.seed(777)
torch.manual_seed(777)
if device == "cuda":
    torch.cuda.manual_seed_all(777)

learning_rate = 0.001
training_epochs = 15
batch_size = 100

mnist_train = dsets.MNIST(root = "",
                          train = True,
                          transform=transforms.ToTensor(),
                          download=True)
mnist_test  = dsets.MNIST(root="",
                          train = False,
                          transform=transforms.ToTensor(),
                          download=True)

data_loader = DataLoader(dataset=mnist_train,
                         batch_size=100,
                         shuffle=True,
                         drop_last=True)

class CNN(torch.nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        
        self.layer1 = torch.nn.Sequential(
            torch.nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))

        self.layer2 = torch.nn.Sequential(
            torch.nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))

        self.fc = torch.nn.Linear(7*7*64, 10, bias=True)

        torch.nn.init.xavier_uniform_(self.fc.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(x)
        out = out.view(out.size(0), -1)

        out = self.fc(out)

        return out


model = CNN().to(device)

criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

total_batch = len(data_loader)

num_data = len(data_loader.dataset)
num_batch = np.ceil(num_data / batch_size)

fn_acc = lambda pred, label:((pred.max(dim=1)[1]==label).type(torch.float)).mean()

start_epoch = 0
for epoch in range(start_epoch+1, training_epochs+1):
    avg_cost = 0
    total_batch = len(data_loader)
    loss_arr = []
    acc_arr = []

    for batch, (x, y) in enumerate (data_loader, 1):
        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()
        hypothesis = model(x)
        cost = criterion(hypothesis, y)
        acc = fn_acc(hypothesis, y)
        cost.backward()
        optimizer.step()

        loss_arr += [cost.item()]
        acc_arr += [acc.item()]
        avg_cost += cost / total_batch
        if batch % 100 == 0:
            print("Train: EPOCH %04d/%04d | BATCH %04d/%04d | LOSS: %.4f | ACC %.4f" 
            %(epoch, training_epochs, batch, num_batch, np.mean(loss_arr), np.mean(acc_arr)))
print("[Epoch: {:>4} cost: {:>.9}".format(epoch+1, avg_cost))

다음 기기로 학습합니다 :  cuda


RuntimeError: Given groups=1, weight of size [64, 32, 3, 3], expected input[100, 1, 28, 28] to have 32 channels, but got 1 channels instead

In [ ]:
import os

def save(ckpt_dir, optim, epoch):
    if not os.path.exists(ckpt_dir):
        os.mkdirs(ckpt_dir)
        torch.save({"net":net.state_dict(),
                    "optim": optim.state_dict()},
                    "./%s/model_epoch%.dpth" %(ckpt_dir, epoch))

def load(ckpt_dir, net, optim):
    ckpt_list =  os.listdir(ckpt_dir)
    ckpt_list.sort()

    dict_model = torch.load()

    net.load_state_dict(dict_model["net"])
    optim.load_state_dic(dict_model["optim"])
    
    return net, optim